#
# Super simple example of a Dockerfile
#
FROM ubuntu:latest
MAINTAINER Addison Freeman "addisonfreeman91@gmail.com"

RUN apt-get update
RUN apt-get install -y python python-pip wget
RUN pip install Flask

CMD ["echo", "hello world"]